### ISSUE TITLE
Enable deselecting dates

### ISSUE THREAD

**Issue by ripla** [ripla/StyleCalendar#8]
This is possible from the server-side but not from the UI. Could be done for example by clicking on the selected date again.

**Comment by Pereitor** [comment]
When I try to select again a date that was just unselected, I have no way of getting it. In this case, StyleCalendar.getValue(); will return null, and also the prop value of the ValueChange event will return null, and the only value I found to return a "valid" value date in this case is getShowingDate(), but that will return just the day the calendar was initialized with. 

I don't see a reason why a just unselected day shouldn't be allowed to be selected again, so I think this should be reopened (or a new bug regarding this should be filled).
